import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import { Akaya_Kanadaka } from 'next/font/google';

const akaya = Akaya_Kanadaka({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-akaya',
})

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'], // Normal, Semi-Bold, Bold e Extra-Bold
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { ReactNode } from 'react'

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br" className={`${poppins.variable} ${akaya.variable} scroll-smooth`}>
      <body className={`bg-slate-900 text-white antialiased font-poppins ${poppins.className}`}>
        <main>{children}</main>
      </body>
    </html>
  )
}
